"""
The loss field per helix unit:  −L'/L(½ + it)  (the completed log-derivative).
Its POLES are the nontrivial zeros — that's where the helix "reads" a zero. On the critical
line the radial-loss component is σ−½ (= 0 on-line). Generated by Σ Λ(n)χ(n)·(winding).
"""
import numpy as np, mpmath as mp, math, os
import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt
mp.mp.dps = 15
OUT = os.path.dirname(os.path.abspath(__file__))

def make_char(q, plus, minus):
    return lambda n: (1 if n % q in plus else (-1 if n % q in minus else 0))

CH = [
  dict(name='ζ  (π/6)', q=1, chi=(lambda n: 1),
       zeros=[14.134725,21.022040,25.010858,30.424876,32.935062,37.586178]),
  dict(name='χ₃ (π/3)', q=3, chi=make_char(3,{1},{2}),
       zeros=[8.0397,11.2492,15.7046,18.2620,20.4558,24.0594,26.5779]),
  dict(name='χ₄ (π/2)', q=4, chi=make_char(4,{1},{3}),
       zeros=[6.0209,10.2438,12.9881,16.3426,18.2920,21.4506,23.2784]),
]

def Lfun(ch):
    q, chi = ch['q'], ch['chi']
    if q == 1:
        return lambda s: mp.zeta(s)
    return lambda s: q**(-s) * mp.fsum(chi(r) * mp.zeta(s, mp.mpf(r)/q) for r in range(1, q+1))

ts = np.linspace(2.0, 40.0, 700)
fig, axes = plt.subplots(len(CH), 1, figsize=(12, 9))
for ax, ch in zip(axes, CH):
    L = Lfun(ch)
    def ld(t):
        s = mp.mpf('0.5') + 1j*mp.mpf(float(t))
        return complex(-mp.diff(L, s) / L(s))
    vals = np.array([abs(ld(t)) for t in ts])
    ax.plot(ts, vals, color='darkgreen', lw=0.9)
    for z in ch['zeros']:
        ax.axvline(z, color='crimson', ls='--', lw=0.8)
    ax.set_yscale('log')
    ax.set_title(f"loss field  |−L'/L(½+it)|   {ch['name']}   — poles (green spikes) at the zeros (red)")
    ax.set_xlabel('height t'); ax.set_ylabel("|−L'/L|"); ax.set_xlim(2, 40)
fig.tight_layout(); fig.savefig(f'{OUT}/loss_field.png', dpi=115)
print(f"saved {OUT}/loss_field.png")
