"""
FIT THE HELIX PHASOR CANCELLATION TO FROBENIUS.

The helix winding wind(t)(n)=n^{it} is FTA-MULTIPLICATIVE (Theta(mn)=Theta(m)+Theta(n)),
so it is generated by the primes: wind(t)(p)=p^{it}.  With the radial weight n^{-sigma},
the prime 'Frobenius eigenvalue' is  alpha_p(s) = p^{-s} = p^{-sigma} * (p^{it})^{-1}.

 (A) sqrt(q)-PURITY = the on-line condition.  |alpha_p|=p^{-sigma}; functional-equation dual
     p^{-(1-s)} has |.|=p^{-(1-sigma)}.  EQUAL <=> sigma=1/2.  So the e^y/sqrt(n) radius IS the
     self-dual sqrt(q)-pure radius (Weil purity, q=p).
 (B) winding SUM == Frobenius/Euler PRODUCT  prod_p det(1-alpha_p)^{-1}  (FTA = Frobenius bridge).
 (C) Frobenius/Lefschetz trace  -zeta'/zeta = sum_p log p * sum_k alpha_p^k.
 (D) zeros = helix winding cancellations at sigma=1/2 = the global Frobenius determinant spectrum.
"""
import numpy as np

def primes_upto(N):
    s = bytearray([1]) * (N + 1); s[0] = s[1] = 0
    for i in range(2, int(N**0.5) + 1):
        if s[i]: s[i*i::i] = bytearray(len(s[i*i::i]))
    return [i for i in range(2, N + 1) if s[i]]
P = np.array(primes_upto(100000), dtype=float)

print("(A) sqrt(q)-PURITY:  |alpha_p| = p^{-sigma}  vs  dual p^{-(1-sigma)};  equal <=> sigma=1/2")
for sigma in [0.5, 0.85]:
    p = P[:6]
    pure = np.allclose(p**(-sigma), p**(-(1 - sigma)))
    tag = "ALL EQUAL -> sqrt(q)-pure / self-dual (UNITARY)" if pure else "unequal -> NOT pure (off the line)"
    print(f"   sigma={sigma}:  |alpha_p|={np.round(p**(-sigma),4)}   dual={np.round(p**(-(1-sigma)),4)}   {tag}")

print("\n(B) winding SUM  ==  Frobenius/Euler PRODUCT   (the FTA = Frobenius bridge, Re s>1)")
def wsum(s, N=2000000):
    n = np.arange(1, N + 1); return np.sum(n.astype(complex)**(-s))
def fprod(s):
    return np.prod(1.0 / (1.0 - P.astype(complex)**(-s)))
for s in [2.0, 2.0 + 10j, 3.0 + 25j]:
    a, b = wsum(s), fprod(s)
    print(f"   s={s}:  sum={np.round(a,7)}   prod={np.round(b,7)}   |d|={abs(a-b):.1e}")

print("\n(C) Frobenius/Lefschetz trace   -zeta'/zeta = sum_p log p * sum_k (Frob_p eigenvalue)^k")
def ftrace(s):
    ps = P.astype(complex)**(-s); return np.sum(np.log(P) * ps / (1 - ps))
for s in [2.0, 3.0 + 25j]:
    print(f"   s={s}:  Tr_Frob = {np.round(ftrace(s),7)}")

print("\n(D) the zeros, ON THE HELIX, at the sqrt(q)-pure radius sigma=1/2 (= global Frobenius spectrum)")
N = 40000; nn = np.arange(1, N + 1, dtype=float); logn = np.log(nn)
alt = np.where((np.arange(1, N + 1) % 2) == 1, 1.0, -1.0)
def zeta_helix(sigma, t):
    eta = np.sum(alt * nn**(-sigma) * np.exp(-1j * t * logn))
    return eta / (1 - 2**(1 - sigma) * np.exp(-1j * t * np.log(2)))
ts = np.arange(8, 42, 0.01)
on = np.abs(np.array([zeta_helix(0.5, t) for t in ts]))
dips = []
for i in range(1, len(on) - 1):
    if on[i] < on[i-1] and on[i] <= on[i+1] and on[i] < 0.2:
        if dips and ts[i] - dips[-1] < 0.8: continue
        dips.append(ts[i])
print(f"   winding cancellations (sigma=1/2): {np.round(dips[:7],3)}")
print(f"   there |alpha_p| = p^(-1/2) = sqrt(q)-pure; off that radius (sigma=0.85) they do not cancel.")
print("""
FIT: the winding IS the Frobenius -- FTA-multiplicative, prime eigenvalues p^{it} on the unit
circle; the radial sqrt(n)=e^{y/2} sets |alpha_p|=p^{-1/2}=sqrt(q)-pure; SUM=PRODUCT is the
Euler=Frobenius bridge; the zeros are the global Frobenius determinant's spectrum, pinned to the
self-dual sqrt(q) radius sigma=1/2 by the e^y geometry.
OPEN (the seam): that the global Frobenius determinant IS xi -- the operator whose Fredholm det
is xi, i.e. its spectrum is EXACTLY the zeros, not merely sharing the sqrt(q) radius.""")
