import RequestProject.HelixReadsGRHZeros

/-!
# Universal Completed Helix Unitarity (helix → circle)

Every generated completed helix mode is unitary. The raw helix grows radially by the native law
`e^{2π/U}` per turn (`U=π/3 ⇒ e⁶`); the completed readout divides that native radius out — radial
growth put into the phase via `helixUnitary` — leaving pure phase `exp(iθ)`, on the unit circle.
Unconditional; no `σ=½` input.
-/

open Complex

namespace HelixReadsGRH

variable {N : ℕ} [NeZero N]

/-- **Universal Completed Helix Unitarity.** Every generated completed helix mode is unitary
(helix → circle):

* (Steps 1–4, 11) the completed readout `sourceRadialPitchWinding σ γ = helixUnitary(σ+γ)` — the
  native radial law divided out, radial put into the phase — lies on the unit circle;
* (Step 7) every finite winding power stays on the circle;
* (Step 6) the grammar is multiplicative: multiplication ↦ winding addition;
* (Step 12) every completed pole's readout lies on the unit circle.

All unconditional. -/
theorem universal_completed_helix_unitarity :
    (∀ σ γ : ℝ, ‖(sourceRadialPitchWinding σ γ : ℂ)‖ = 1) ∧
    (∀ σ γ : ℝ, ∀ M : ℕ, ‖(sourceRadialPitchWinding σ γ : ℂ) ^ M‖ = 1) ∧
    (∀ s t : ℝ, helixUnitary (s + t) = helixUnitary s * helixUnitary t) ∧
    (∀ (χ : DirichletCharacter ℂ N) (ρ : ℂ), CompletedLogDerivPole χ ρ → ∀ M : ℕ,
        ‖(sourceWindingLossReadout ρ : ℂ) ^ M‖ = 1) :=
  ⟨sourceRadialPitchWinding_norm,
   sourceRadialPitchWinding_pow_norm,
   helixUnitary_add,
   fun _ ρ _ M => sourceWindingLossReadout_pow_norm ρ M⟩

/-- **Pole version (Step 12), standalone.** The completed readout of every pole generated by the
helix grammar lies on the unit circle. -/
theorem completed_pole_readout_unitary (χ : DirichletCharacter ℂ N) (ρ : ℂ)
    (_hρ : CompletedLogDerivPole χ ρ) :
    ‖(sourceWindingLossReadout ρ : ℂ)‖ = 1 := by
  simpa using sourceWindingLossReadout_pow_norm ρ 1

end HelixReadsGRH

#print axioms HelixReadsGRH.universal_completed_helix_unitarity
#print axioms HelixReadsGRH.completed_pole_readout_unitary
