import mpmath as mp
mp.mp.dps = 25
def ns(x,n=8): return mp.nstr(x,n)

print("="*72)
print("HEIGHT z GENERATED BY THE CLIMB (not a dial)")
print("="*72)
print("""
 climb:    z = pitch * (loops k)              -> z is the axial coordinate
 area law: integers by loop k  ~  alpha*k^2   -> active count N(z) ~ beta*z^2
 readout:  log enters only at 2D->1D:  finite sum over the wound integers
           R(z) = sum_{n=1}^{N(z)} (-1)^{n-1} n^{-1/2} e^{-i z log n}
 the first crossing is the first climb height z where R(z) cancels.
""")

def readout(z, beta):
    N = max(1, int(mp.floor(beta*z*z)))
    s = mp.mpc(0)
    for n in range(1, N+1):
        s += ((-1)**(n-1))*mp.mpf(n)**(mp.mpf(-1)/2)*mp.e**(-1j*z*mp.log(n))
    return s, N

g1 = mp.im(mp.zetazero(1))
for beta in [mp.mpf('1.0'), mp.mpf('0.5'), mp.mpf('2.0')]:
    best=None; bz=None
    z=mp.mpf('8.0')
    while z < mp.mpf('20.0'):
        v=abs(readout(z,beta)[0])
        if best is None or v<best: best=v; bz=z
        z+=mp.mpf('0.1')
    _,N = readout(bz,beta)
    print(f" beta={ns(beta,3):>5}: first crossing at climb z = {ns(bz,6)}  "
          f"(|R|={ns(best,4)}, active N={N})   gamma_1={ns(g1,8)}")

print("\n compare: the climb sets the z-axis and how many integers are active;")
print(" where R(z) actually cancels is fixed by the log-readout (the n^{it} phases).")
